/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigModel } from './ConfigModel';
import {
    ConfigModelFromJSON,
    ConfigModelFromJSONTyped,
    ConfigModelToJSON,
    ConfigModelToJSONTyped,
} from './ConfigModel';

/**
 * Global configuration snapshot for frontend.
 * @export
 * @interface GlobalConfig
 */
export interface GlobalConfig {
    /**
     * Current default model key
     * @type {string}
     * @memberof GlobalConfig
     */
    defaultModel: string;
    /**
     * Current default thinking mode
     * @type {boolean}
     * @memberof GlobalConfig
     */
    defaultThinking: boolean;
    /** Active value from [thinking].effort. */
    thinkingEffort: string;
    /**
     * Current default plan mode
     * @type {boolean}
     * @memberof GlobalConfig
     */
    defaultPlanMode: boolean;
    /**
     * Current default permission mode from Kimi Code
     * @type {string}
     * @memberof GlobalConfig
     */
    defaultPermissionMode: string;
    /**
     * All configured models
     * @type {Array<ConfigModel>}
     * @memberof GlobalConfig
     */
    models: Array<ConfigModel>;
}

/**
 * Check if a given object implements the GlobalConfig interface.
 */
export function instanceOfGlobalConfig(value: object): value is GlobalConfig {
    if (!('defaultModel' in value) || value['defaultModel'] === undefined) return false;
    if (!('defaultThinking' in value) || value['defaultThinking'] === undefined) return false;
    if (!('thinkingEffort' in value) || value['thinkingEffort'] === undefined) return false;
    if (!('defaultPlanMode' in value) || value['defaultPlanMode'] === undefined) return false;
    if (!('defaultPermissionMode' in value) || value['defaultPermissionMode'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    return true;
}

export function GlobalConfigFromJSON(json: any): GlobalConfig {
    return GlobalConfigFromJSONTyped(json, false);
}

export function GlobalConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModel': json['default_model'],
        'defaultThinking': json['default_thinking'],
        'thinkingEffort': json['thinking_effort'] ?? '',
        'defaultPlanMode': Boolean(json['default_plan_mode']),
        'defaultPermissionMode': json['default_permission_mode'] ?? 'manual',
        'models': ((json['models'] as Array<any>).map(ConfigModelFromJSON)),
    };
}

export function GlobalConfigToJSON(json: any): GlobalConfig {
    return GlobalConfigToJSONTyped(json, false);
}

export function GlobalConfigToJSONTyped(value?: GlobalConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model': value['defaultModel'],
        'default_thinking': value['defaultThinking'],
        'thinking_effort': value['thinkingEffort'],
        'default_plan_mode': value['defaultPlanMode'],
        'default_permission_mode': value['defaultPermissionMode'],
        'models': ((value['models'] as Array<any>).map(ConfigModelToJSON)),
    };
}
